//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFilm.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WebFilmEntities2 : DbContext
    {
        public WebFilmEntities2()
            : base("name=WebFilmEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Table_CaTaLog> Table_CaTaLog { get; set; }
        public virtual DbSet<Table_CauHinh> Table_CauHinh { get; set; }
        public virtual DbSet<Table_Comment> Table_Comment { get; set; }
        public virtual DbSet<Table_Fim> Table_Fim { get; set; }
        public virtual DbSet<Table_GiaoDienWed> Table_GiaoDienWed { get; set; }
        public virtual DbSet<table_QuangCao> table_QuangCao { get; set; }
        public virtual DbSet<Table_TheLoai> Table_TheLoai { get; set; }
        public virtual DbSet<Table_TinTuc> Table_TinTuc { get; set; }
        public virtual DbSet<Table_Trailer> Table_Trailer { get; set; }
        public virtual DbSet<Table_Username> Table_Username { get; set; }
        public virtual DbSet<Table_YeuCau> Table_YeuCau { get; set; }
    }
}
