//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFilm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class table_QuangCao
    {
        public int IDQuangCao { get; set; }
        public string NameQC { get; set; }
        public string DiaChiUrlQC { get; set; }
        public string AnhQC { get; set; }
        public Nullable<int> IDUserName { get; set; }
    
        public virtual Table_Username Table_Username { get; set; }
    }
}
