//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFilm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Fim
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Table_Fim()
        {
            this.Table_Comment = new HashSet<Table_Comment>();
            this.Table_Trailer = new HashSet<Table_Trailer>();
            this.Table_YeuCau = new HashSet<Table_YeuCau>();
        }
    
        public int IDFim { get; set; }
        public string NameFim { get; set; }
        public Nullable<int> IDTheLoai { get; set; }
        public string TenDienVien { get; set; }
        public string AnhDienVien { get; set; }
        public string ThongTinBoFim { get; set; }
        public string DaoDien { get; set; }
        public Nullable<int> NamSanXuat { get; set; }
        public string NoiSanXuat { get; set; }
        public string Rating { get; set; }
        public Nullable<int> IDUserName { get; set; }
        public string AnhPhim { get; set; }
        public string Slide { get; set; }
        public string url { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_Comment> Table_Comment { get; set; }
        public virtual Table_TheLoai Table_TheLoai { get; set; }
        public virtual Table_Username Table_Username { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_Trailer> Table_Trailer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_YeuCau> Table_YeuCau { get; set; }
    }
}
