//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFilm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Comment
    {
        public int IDComment { get; set; }
        public string NameCommenFim { get; set; }
        public string NamePoster { get; set; }
        public string NDComment { get; set; }
        public Nullable<int> IDFim { get; set; }
    
        public virtual Table_Fim Table_Fim { get; set; }
    }
}
