//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFilm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_TheLoai
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Table_TheLoai()
        {
            this.Table_Fim = new HashSet<Table_Fim>();
        }
    
        public int IDTheLoai { get; set; }
        public string NameTheLoai { get; set; }
        public string MoTa { get; set; }
        public Nullable<bool> HienThiTL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_Fim> Table_Fim { get; set; }
    }
}
