//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFilm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_CauHinh
    {
        public int IDCauHinh { get; set; }
        public string NameCauHinh { get; set; }
        public Nullable<int> IDUserName { get; set; }
        public Nullable<bool> GiaTriTrangThai { get; set; }
        public string SkinMD { get; set; }
        public Nullable<int> SoTrangWed { get; set; }
        public string ThongBao { get; set; }
        public string CauHinhNow { get; set; }
    
        public virtual Table_Username Table_Username { get; set; }
    }
}
